export const QUERY_KEYS = {
  GET_CAT: 'get-categories',
  GET_TAGS: 'get-tags',
  GET_COLLECTIONS_NAME: 'collection-name',
  GET_COLLECTION: 'get-collection-by-id',
  GET_DASHBOARD_COLLECTIONS:'get-dashboard-collection-nfts',
  GET_MY_COLLECTION:'get-collection',
  GET_COLLECTION_BY_CAT_ID:'get-collection-by-cat-id',
  GET_PROFILE : 'get-profile-by-id',
  GET_COLLECTION_DETAIL:'get-collection-detail',
  GET_COLLECTION_NFTS_BY_ID:'get-collection-Nfts-by-id',
  GET_NFT_DETAIL:'get-nft-detail',
  GET_MORE_NFTS_BY_COLLECTION:'get-more-nft-by-collection',
  GET_BANNER_COLLECTION:'get-banner-collection',
  GET_ALL_COLLECTIONS:'get-all-collections', 
  GET_ACTIVITIES: 'get-all-activities',
  GET_USER:'get-profile',
  GET_COLLECTION_BY_USER_ID:'get-collections-by-userId',
  GET_SIGN: "get-sign",
  CREATE_NOTIFICATION:'create-notification',
  GET_USER_NFTS:'get-user-nfts',
  GET_STATS:'get-stats',
  ADD_TO_WATCHLIST:'add-to-watchlist',
  REMOVE_FROM_WATCHLIST:'remove-from-watchlist',
  GET_BAR_CHART: 'get-bar-chart',
  GET_LINE_CHART: 'get-line-chart',
  GET_DOT_CHART: 'get-sale-chart',
  GET_COLLECTION_ACTIVITIES: 'get-collection-activities',
  GET_NFT_ACTIVITIES:'get-nft-activites',
  GET_All_COLLECTIONS_NAME:'get-all-collections-name',
  GET_USER_ACTIVITES:'get-all-user-activites',
  GET_COLLECTION_PROPERTIES:'get-collection-properties',
  GET_TOPTEN_COLLECTIONS:'get-top-ten-collections',
  GET_ANALYTICS_LISTING:'stat-listing-nft',
  GET_TOP_OWNERS:'stat-top-owner',
  GET_TOP_OWNER_DISTRIBUTION:'owner-distribution',
  GET_NOTIF_SETTINGS: 'get-notif-settings',
  GET_SEARCH_COLLECTIONS:'get-search-collections',
  GET_WATCHLIST:'stats/get-watchlist-collection',
  GET_COLLECTED_NFT:'get-collected-nfts'
};
