export const ApiUrl = {
  PIN_FILE_TO_IPS: "pinning/pinFileToIPFS",
  UPLOAD_FILE_TO_SERVER: "collection/upload",
  GET_CATEGORIES: "minting/get-categories",
  GET_TAGS: "tag/get-tags",
  CREATE_COLLECTION: "collection",
  GET_COLLECTIONS_NAME: "collection/get-collection-name",
  UPDATE_COLLECTION_ADDRESS: "collection/update-contract-address",
  UPDATE_NFT_MINT_DATA: "activity/create-activity",
  CREATE_NFT: "minting/create-nft",
  GET_COLLECTION: "collection/editCollectionById",
  GET_DASHBOARD_COLLECTION: "minting/get-dashboard-collection-nfts",
  GET_MY_COLLECTION: "collection/getCollectionsByWalletAddress",
  GET_COLLECTION_BY_CAT_ID: "collection/get-collections-by-category-id",
  GET_PROFILE_BY_ID: "user/get-profile",
  UPDATE_PROFILE: "user/update-user",
  GET_COLLECTION_DETAIL: "collection/getCollectionsById",
  GET_COLLECTION_NFTS_BY_ID: "minting/nfts-by-collection-id",
  GET_NFT_DETAIL: "minting/nfts-details-by-id/",
  GET_MORE_NFTS_BY_COLLECTION: "minting/more-nfts-by-collection",
  GET_BANNER_COLLECTION: "collection/get-banner-collection",
  GET_ALL_COLLECTIONS: "collection/get-collections",
  GET_ACTIVITIES: "collection/get-activities",
  GET_USER: "user/get-profile",
  GET_COLLECTION_BY_USER_ID: "collection/getCollectionsByWalletAddress",
  SAVE_SIGNATURE: "user/connect-wallet",
  GET_SIGNATURE: "user/get-user-walletAddress",
  CREATE_NOTIFICATION: "user/send-notification",
  LIST_FOR_SALE: "nft-listing/list-nft",
  GET_USER_NFTS: "minting/get-user-nfts",
  GET_STATS:'stats/collection-stats',
  ADD_TO_WATCHLIST:'}user/add-to-watchlist'
};
